// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: rpc/v1/master.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	mi := &file_rpc_v1_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_master_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GreetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetResponse) Reset() {
	*x = GreetResponse{}
	mi := &file_rpc_v1_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResponse) ProtoMessage() {}

func (x *GreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResponse.ProtoReflect.Descriptor instead.
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_master_proto_rawDescGZIP(), []int{1}
}

func (x *GreetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_v1_master_proto protoreflect.FileDescriptor

const file_rpc_v1_master_proto_rawDesc = "" +
	"\n" +
	"\x13rpc/v1/master.proto\x12\x06rpc.v1\"\"\n" +
	"\fGreetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\rGreetResponse\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2G\n" +
	"\rMasterService\x126\n" +
	"\x05Greet\x12\x14.rpc.v1.GreetRequest\x1a\x15.rpc.v1.GreetResponse\"\x00B@Z>github.com/nlduy0310/simple-distributed-mapreduce/rpc/v1;rpcv1b\x06proto3"

var (
	file_rpc_v1_master_proto_rawDescOnce sync.Once
	file_rpc_v1_master_proto_rawDescData []byte
)

func file_rpc_v1_master_proto_rawDescGZIP() []byte {
	file_rpc_v1_master_proto_rawDescOnce.Do(func() {
		file_rpc_v1_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_v1_master_proto_rawDesc), len(file_rpc_v1_master_proto_rawDesc)))
	})
	return file_rpc_v1_master_proto_rawDescData
}

var file_rpc_v1_master_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_v1_master_proto_goTypes = []any{
	(*GreetRequest)(nil),  // 0: rpc.v1.GreetRequest
	(*GreetResponse)(nil), // 1: rpc.v1.GreetResponse
}
var file_rpc_v1_master_proto_depIdxs = []int32{
	0, // 0: rpc.v1.MasterService.Greet:input_type -> rpc.v1.GreetRequest
	1, // 1: rpc.v1.MasterService.Greet:output_type -> rpc.v1.GreetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_v1_master_proto_init() }
func file_rpc_v1_master_proto_init() {
	if File_rpc_v1_master_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_v1_master_proto_rawDesc), len(file_rpc_v1_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_v1_master_proto_goTypes,
		DependencyIndexes: file_rpc_v1_master_proto_depIdxs,
		MessageInfos:      file_rpc_v1_master_proto_msgTypes,
	}.Build()
	File_rpc_v1_master_proto = out.File
	file_rpc_v1_master_proto_goTypes = nil
	file_rpc_v1_master_proto_depIdxs = nil
}
