// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rpc/v1/master.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_rpc_v1_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_master_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_rpc_v1_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_master_proto_rawDescGZIP(), []int{1}
}

var File_rpc_v1_master_proto protoreflect.FileDescriptor

const file_rpc_v1_master_proto_rawDesc = "" +
	"\n" +
	"\x13rpc/v1/master.proto\x12\x06rpc.v1\"'\n" +
	"\x15RegisterWorkerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16RegisterWorkerResponse2b\n" +
	"\rMasterService\x12Q\n" +
	"\x0eRegisterWorker\x12\x1d.rpc.v1.RegisterWorkerRequest\x1a\x1e.rpc.v1.RegisterWorkerResponse\"\x00B@Z>github.com/nlduy0310/simple-distributed-mapreduce/rpc/v1;rpcv1b\x06proto3"

var (
	file_rpc_v1_master_proto_rawDescOnce sync.Once
	file_rpc_v1_master_proto_rawDescData []byte
)

func file_rpc_v1_master_proto_rawDescGZIP() []byte {
	file_rpc_v1_master_proto_rawDescOnce.Do(func() {
		file_rpc_v1_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_v1_master_proto_rawDesc), len(file_rpc_v1_master_proto_rawDesc)))
	})
	return file_rpc_v1_master_proto_rawDescData
}

var file_rpc_v1_master_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_v1_master_proto_goTypes = []any{
	(*RegisterWorkerRequest)(nil),  // 0: rpc.v1.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 1: rpc.v1.RegisterWorkerResponse
}
var file_rpc_v1_master_proto_depIdxs = []int32{
	0, // 0: rpc.v1.MasterService.RegisterWorker:input_type -> rpc.v1.RegisterWorkerRequest
	1, // 1: rpc.v1.MasterService.RegisterWorker:output_type -> rpc.v1.RegisterWorkerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_v1_master_proto_init() }
func file_rpc_v1_master_proto_init() {
	if File_rpc_v1_master_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_v1_master_proto_rawDesc), len(file_rpc_v1_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_v1_master_proto_goTypes,
		DependencyIndexes: file_rpc_v1_master_proto_depIdxs,
		MessageInfos:      file_rpc_v1_master_proto_msgTypes,
	}.Build()
	File_rpc_v1_master_proto = out.File
	file_rpc_v1_master_proto_goTypes = nil
	file_rpc_v1_master_proto_depIdxs = nil
}
