// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rpc/v1/worker.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapRequest) Reset() {
	*x = MapRequest{}
	mi := &file_rpc_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapRequest) ProtoMessage() {}

func (x *MapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapRequest.ProtoReflect.Descriptor instead.
func (*MapRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_worker_proto_rawDescGZIP(), []int{0}
}

type MapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapResponse) Reset() {
	*x = MapResponse{}
	mi := &file_rpc_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapResponse) ProtoMessage() {}

func (x *MapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapResponse.ProtoReflect.Descriptor instead.
func (*MapResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_worker_proto_rawDescGZIP(), []int{1}
}

var File_rpc_v1_worker_proto protoreflect.FileDescriptor

const file_rpc_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x13rpc/v1/worker.proto\x12\x06rpc.v1\"\f\n" +
	"\n" +
	"MapRequest\"\r\n" +
	"\vMapResponse2A\n" +
	"\rWorkerService\x120\n" +
	"\x03Map\x12\x12.rpc.v1.MapRequest\x1a\x13.rpc.v1.MapResponse\"\x00B@Z>github.com/nlduy0310/simple-distributed-mapreduce/rpc/v1;rpcv1b\x06proto3"

var (
	file_rpc_v1_worker_proto_rawDescOnce sync.Once
	file_rpc_v1_worker_proto_rawDescData []byte
)

func file_rpc_v1_worker_proto_rawDescGZIP() []byte {
	file_rpc_v1_worker_proto_rawDescOnce.Do(func() {
		file_rpc_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_v1_worker_proto_rawDesc), len(file_rpc_v1_worker_proto_rawDesc)))
	})
	return file_rpc_v1_worker_proto_rawDescData
}

var file_rpc_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_v1_worker_proto_goTypes = []any{
	(*MapRequest)(nil),  // 0: rpc.v1.MapRequest
	(*MapResponse)(nil), // 1: rpc.v1.MapResponse
}
var file_rpc_v1_worker_proto_depIdxs = []int32{
	0, // 0: rpc.v1.WorkerService.Map:input_type -> rpc.v1.MapRequest
	1, // 1: rpc.v1.WorkerService.Map:output_type -> rpc.v1.MapResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_v1_worker_proto_init() }
func file_rpc_v1_worker_proto_init() {
	if File_rpc_v1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_v1_worker_proto_rawDesc), len(file_rpc_v1_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_v1_worker_proto_goTypes,
		DependencyIndexes: file_rpc_v1_worker_proto_depIdxs,
		MessageInfos:      file_rpc_v1_worker_proto_msgTypes,
	}.Build()
	File_rpc_v1_worker_proto = out.File
	file_rpc_v1_worker_proto_goTypes = nil
	file_rpc_v1_worker_proto_depIdxs = nil
}
