FROM docker.io/golang:1.26-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /bin/master ./cmd/master


FROM scratch

ENV PORT=8000

COPY --from=build /bin/master /bin/master

ENTRYPOINT ["/bin/master"]
