services:
  master:
    container_name: master
    build:
      context: .
      dockerfile: build/master/Dockerfile
    command:
      - "--port"
      - "8000"
      - "--advertise-address"
      - "master:8000"

  worker-1:
    container_name: worker-1
    build:
      context: .
      dockerfile: build/worker/Dockerfile
    command:
      - "--name"
      - "worker-1"
      - "--port"
      - "5000"
      - "--advertise-address"
      - "worker-1:5000"
      - "--master-address"
      - "master:8000"
      - "--heartbeat-interval"
      - "5"
    depends_on:
      - master

  worker-2:
    container_name: worker-2
    build:
      context: .
      dockerfile: build/worker/Dockerfile
    command:
      - "--name"
      - "worker-2"
      - "--port"
      - "5000"
      - "--advertise-address"
      - "worker-2:5000"
      - "--master-address"
      - "master:8000"
      - "--heartbeat-interval"
      - "2"
    depends_on:
      - master
